name: dino_finder
description: Dinosaur classification with TensorFlow lite.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera: ^0.5.6+3
  tflite: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
